server:
  port: ${SERVER_PORT:12306}

spring:
  application:
    name: review-service
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
